### ISSUE TITLE
Edit the Search Engines section

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#937]
https://fmhy.net/adblockvpnguide#search-engines

I suggest the following:

- Removing [DDG](https://html.duckduckgo.com/html) and instead putting [Metager](https://metager.org).
- Removing kagi as it's not free to use, thus listing it will be a free advertisement.
- Removing [Mojeek](https://www.mojeek.com/) and instead replace it with [Stract](https://trystract.com)|[Alexandria](https://www.alexandria.org).

**Comment by nbats** [comment]
Alright thank you, I removed Kagi and added Stract, but we already have metager. As far as removing DDG + Mojeek goes, we'll need some sort of reasoning as lots of people use them, especially DDG.

**Comment by nullish-cat** [comment]
DDG has weird censorship regarding the Ukraine-Russia war, primarily uses Bing for its index, and their website is closed source. As for Mojeek, I'm assuming it's because of the quality of the results? Cause otherwise it's pretty good, [privacy policy states they collect no identifiable data.](https://www.mojeek.com/about/privacy/)

**Comment by nbats** [comment]
Yeah that's fair I just don't know if any of it is enough to remove DDG or even unstar it. People have been using it for years now with no privacy issues as far as I know.

**Comment by nullish-cat** [comment]
Looking at their [privacy policy](https://duckduckgo.com/privacy), they seem to store search queries and "analyze anonymous trends like popular searches":

> For example, we may know that we got a lot of searches for "[cute cat pictures](https://duckduckgo.com/?q=cute+cat+pictures&iax=images&ia=images)" today, but we don’t know who actually performed those searches. That is, viewing search results on DuckDuckGo is anonymous. And we only save these anonymous search queries — completely disconnected from any unique identifiers like IP addresses — for just enough time to analyze anonymous trends like popular searches, so that we can better serve you.

They also have ads based off of those searches:

> It is a myth that search engines need to track you to make money. We make our money from [private search ads](https://duckduckgo.com/duckduckgo-help-pages/company/advertising-and-affiliates/) on our search engine. On most other search engines, ads are influenced by profiles compiled from your personal information, such as search, browsing, and purchase history. Since we don’t have that information, search ads on DuckDuckGo are based on the search results page you’re viewing, and not based on you as a person. For example, if you search for cars, we’ll show you ads about cars.

The only other listed engine that does this is [Stract](https://trystract.com/privacy-and-happy-lawyers), which uses it for "training its ranking models." ([Metager](https://metager.org/datenschutz) also states it temporarily stores queries but only because of caching.) That being said, I'm not OP, and I'd like to see their own reasoning as well.

**Comment by XCE0** [comment]
My own reasoning is similar to yours, I think that DDG has bad privacy policy and mojeek has bad results compared to alternatives, I think they are not worthy to recommend.

**Comment by nbats** [comment]
Alright I starred Metager and Stract, but DDG is so popular and again I've never actually heard of a single person ever having actual issues in terms of their privacy with them. If we can find some sort of example of their privacy policy actually being an issue somehow we can reconsider.

Right now the starred order is this: 

SearXNG
Metager
Stract
DDG
